//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYDS.Storage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AtYourDoorStepEntities : DbContext
    {
        public AtYourDoorStepEntities()
            : base("name=AtYourDoorStepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAYDSAddressInformation> tblAYDSAddressInformations { get; set; }
        public virtual DbSet<tblAYDSAddressType> tblAYDSAddressTypes { get; set; }
        public virtual DbSet<tblAYDSBookingDetail> tblAYDSBookingDetails { get; set; }
        public virtual DbSet<tblAYDSBookingStatu> tblAYDSBookingStatus { get; set; }
        public virtual DbSet<tblAYDSCity> tblAYDSCities { get; set; }
        public virtual DbSet<tblAYDSCountry> tblAYDSCountries { get; set; }
        public virtual DbSet<tblAYDSParcelDetail> tblAYDSParcelDetails { get; set; }
        public virtual DbSet<tblAYDSParcelType> tblAYDSParcelTypes { get; set; }
        public virtual DbSet<tblAYDSState> tblAYDSStates { get; set; }
        public virtual DbSet<tblAYDSTrackingInformation> tblAYDSTrackingInformations { get; set; }
        public virtual DbSet<tblAYDSUserInformation> tblAYDSUserInformations { get; set; }
    
        public virtual ObjectResult<GetBookingHistory_Result> GetBookingHistory(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBookingHistory_Result>("GetBookingHistory", userIdParameter);
        }
    }
}
