//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYDS.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAYDSCity
    {
        public tblAYDSCity()
        {
            this.tblAYDSAddressInformations = new HashSet<tblAYDSAddressInformation>();
            this.tblAYDSUserInformations = new HashSet<tblAYDSUserInformation>();
        }
    
        public int CityId { get; set; }
        public string City { get; set; }
        public int Country { get; set; }
        public int State { get; set; }
        public int PinCode { get; set; }
    
        public virtual ICollection<tblAYDSAddressInformation> tblAYDSAddressInformations { get; set; }
        public virtual tblAYDSCountry tblAYDSCountry { get; set; }
        public virtual tblAYDSState tblAYDSState { get; set; }
        public virtual ICollection<tblAYDSUserInformation> tblAYDSUserInformations { get; set; }
    }
}
