//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYDS.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAYDSBookingDetail
    {
        public tblAYDSBookingDetail()
        {
            this.tblAYDSTrackingInformations = new HashSet<tblAYDSTrackingInformation>();
        }
    
        public string BookingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> RecieverId { get; set; }
        public Nullable<int> ParcleType { get; set; }
        public Nullable<System.DateTime> BookingDateTime { get; set; }
        public Nullable<System.DateTime> EstimatedDeliveyDateTime { get; set; }
        public Nullable<int> BookingStatus { get; set; }
    
        public virtual tblAYDSAddressInformation tblAYDSAddressInformation { get; set; }
        public virtual tblAYDSAddressInformation tblAYDSAddressInformation1 { get; set; }
        public virtual tblAYDSParcelDetail tblAYDSParcelDetail { get; set; }
        public virtual tblAYDSUserInformation tblAYDSUserInformation { get; set; }
        public virtual ICollection<tblAYDSTrackingInformation> tblAYDSTrackingInformations { get; set; }
    }
}
