//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYDS.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAYDSUserLoginDetail
    {
        public tblAYDSUserLoginDetail()
        {
            this.tblAYDSAddressInformations = new HashSet<tblAYDSAddressInformation>();
            this.tblAYDSBookingDetails = new HashSet<tblAYDSBookingDetail>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsVerified { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastLogin { get; set; }
        public bool IsActivated { get; set; }
    
        public virtual ICollection<tblAYDSAddressInformation> tblAYDSAddressInformations { get; set; }
        public virtual ICollection<tblAYDSBookingDetail> tblAYDSBookingDetails { get; set; }
    }
}
