//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYDS.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAYDSParcelType
    {
        public tblAYDSParcelType()
        {
            this.tblAYDSParcelDetails = new HashSet<tblAYDSParcelDetail>();
        }
    
        public int Id { get; set; }
        public string ParcleType { get; set; }
    
        public virtual ICollection<tblAYDSParcelDetail> tblAYDSParcelDetails { get; set; }
    }
}
