//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYDS.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAYDSAddressInformation
    {
        public tblAYDSAddressInformation()
        {
            this.tblAYDSBookingDetails = new HashSet<tblAYDSBookingDetail>();
            this.tblAYDSBookingDetails1 = new HashSet<tblAYDSBookingDetail>();
        }
    
        public int AddressInfoId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AddressType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Landmark { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> PinCode { get; set; }
        public Nullable<int> Contact1 { get; set; }
        public Nullable<int> Contact2 { get; set; }
        public string EmailId { get; set; }
        public string AddressNickName { get; set; }
    
        public virtual tblAYDSAddressType tblAYDSAddressType { get; set; }
        public virtual tblAYDSCity tblAYDSCity { get; set; }
        public virtual tblAYDSCountry tblAYDSCountry { get; set; }
        public virtual tblAYDSUserInformation tblAYDSUserInformation { get; set; }
        public virtual ICollection<tblAYDSBookingDetail> tblAYDSBookingDetails { get; set; }
        public virtual ICollection<tblAYDSBookingDetail> tblAYDSBookingDetails1 { get; set; }
    }
}
