//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYDS.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAYDSUserInformation
    {
        public int UserInfoId { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public int MobileNumber { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public string CountryCode { get; set; }
    
        public virtual tblAYDSCity tblAYDSCity { get; set; }
        public virtual tblAYDSCountry tblAYDSCountry { get; set; }
    }
}
