//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYDS.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAYDSParcelDetail
    {
        public tblAYDSParcelDetail()
        {
            this.tblAYDSBookingDetails = new HashSet<tblAYDSBookingDetail>();
        }
    
        public int ParcelId { get; set; }
        public int ParcelType { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Breadth { get; set; }
        public Nullable<decimal> Height { get; set; }
    
        public virtual ICollection<tblAYDSBookingDetail> tblAYDSBookingDetails { get; set; }
        public virtual tblAYDSParcelType tblAYDSParcelType { get; set; }
    }
}
